### ISSUE TITLE
Building your project

### ISSUE THREAD

**Issue by Belval** [magnificus/Procedural-Cities#13]
Hi!

Your project looks great, but I cannot seem to get it to compile on Ubuntu 18.04 targeting Unreal Engine 4.19.

My error messages are:

    error: '&&' within '||' [-Werror,-Wlogical-op-parentheses]
    error: call to 'abs' is ambiguous
        
I do not really care about UE's version so if you got it to work with a precise version I'd be willing to give it a shot.

**Comment by RaceTheMaSe** [comment]
This needs parentheses around (std::abs) and maybe in the expression itself. ( (a && b) || ( c && d) ) where the error occurs.

**Comment by Belval** [comment]
That was my guess, but I suppose the project used to compile without error on a previous version.

**Comment by Belval** [comment]
Successfully built the project on Windows. I suppose it's just not compatible with Linux.
