### ISSUE TITLE
Can Launch UE4.25 project, but Magic Leap Structs have changed. Any Ideas how to fix this?

### ISSUE THREAD

**Issue by tdw46** [magnificus/Procedural-Cities#18]
Looks like the structs for magic leap have changed so they don't match the format that this was originally programmed for. Any ideas how to get the description and transform information from the magic leap tracking mesh struct now?
![image](https://user-images.githubusercontent.com/10996763/115987501-5167fb80-a583-11eb-9d17-32d7b1136e83.png)

**Comment by tdw46** [comment]
Of course, this also means any references to your current structs mismatch magic leap connections now:

![image](https://user-images.githubusercontent.com/10996763/115987619-d18e6100-a583-11eb-87a9-277b156f7e33.png)

**Comment by VietnamHightechGroup** [comment]
disabling all the Magic Leap plugins
